### ISSUE TITLE
Reports `firstPaint` as SpeedIndex in current Chrome

### ISSUE THREAD

**Issue by lyio** [WPO-Foundation/RUM-SpeedIndex#10]
The Regex `var re = /url\((http.*)\)/ig;` does not account for additional `"` that Chrome has in the object returned by `window.getComputedStyles`.

The value of the field `background-image` is `url("https://localhost/Fioport.Vermarktung.Demo/Fioport.Vermarktung.Frontend/assets/img/login_1920x1080.jpg")` in Chrome 52 and 53 whereas it is `url(https://localhost/Fioport.Vermarktung.Demo/Fioport.Vermarktung.Frontend/assets/img/login_1920x1080.jpg)` in Edge 25 (and I guess older versions of Chrome).

I replaced the `"` with an empty string like this `CheckElement(el, matches[1].replace('"', ''));` and got similar results in Edge and Chrome.

I am reluctant to open a PR for this as this project has not seen any updates in a long time.

**Comment by pmeenan** [comment]
Fixed with your PR.  Thanks.
