### ISSUE TITLE
Allow it to only run on browsers that support First Paint

### ISSUE THREAD

**Issue by grantkemp** [WPO-Foundation/RUM-SpeedIndex#14]
We are currently logging the speed index- it would be excellent if we can choose to only run it on certain browsers.  namely Chrome, IE and Edge which support first paint so we can make sure we are logging the most accurate number and are not pushed out by other browsers with weaker support.

**Comment by soulgalore** [comment]
Hey @grantkemp you can do a wrapper yourself that checks if chrome/ie firstPaint is supported and then run the script? Or how do you want it to change :)

Best
Peter

**Comment by grantkemp** [comment]
Yes- actually it does make sense to do it outside the library.
