### ISSUE TITLE
Suggestion : Improved Documentation about code placement/  trigger?

### ISSUE THREAD

**Issue by grantkemp** [WPO-Foundation/RUM-SpeedIndex#15]
Hi 
We are looking to include this on a website to keep track of the performance for users, and it would be useful to know what would be the best time to include the snippet where we calculate the Speed Index. 
-  If we put it in the header - it will obviosly be quite low and miss out elements like images etc. 
- If we put it after dom is loaded then it will miss out on some async scripts  and lazy loaded images. 

Is there a recommended place to put the code- that we can perhaps add to Readme?

**Comment by pmeenan** [comment]
Usually you want to gather this kind of page metric after onload.  That way you know all of the page resources have loaded (unless you are using a single-page-app framework then it's up to you to decide when).

**Comment by pmeenan** [comment]
It's worth noting that DOM Loaded will still miss out on MOST images, not just lazy-loaded ones.

**Comment by grantkemp** [comment]
Thanks @pmeenan. 
  so ideally we should have it loaded 
```<body onload="runSpeedTest()">```

**Comment by pmeenan** [comment]
In principle though in actual code you'll want to use window.addEventListener
