### ISSUE TITLE
Deprecated chrome.loadTimes()

### ISSUE THREAD

**Issue by GuillaumeRossolini** [WPO-Foundation/RUM-SpeedIndex#16]
Hi,

I am using your lib to send the RUM Speed Index to Google Analytics as a metric.

Unfortunately, Chrome has been sending the following in DevTools' console for a while (I am using the Canary channel):

> [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing. https://www.chromestatus.com/features/5637885046816768.
> [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.

By chance, are there plans to switch this in this library?

Thanks,

**Comment by gigabo** [comment]
Looks like this was closed with no comment. Was there some discussion elsewhere?

**Comment by GuillaumeRossolini** [comment]
@pmeenan I'm sorry I don't understand, I have the latest trunk but I still get warnings in the console.
